SRAM/Controllers/AssignController.cs
using BisnessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SRAM.Controllers
{
    public class AssignController : Controller
    {
        /// <summary>
        /// Permite obtener las cuentas pendientes en asignar.
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Index()
        {
            ViewBag.totalAsignado = 0;
            List<Entities.UnAssignedAudit> unAssignedAudits = new AuditoriaBusiness().GetUnAssignedAudit();
            return View(unAssignedAudits);
        }

        /// <summary>
        /// Permite asignar cuentas a usuarios.
        /// </summary>
        /// <param name="date">Fechas de las asignaciones</param>
        /// <param name="auditor">Usuarios a quienes le seran asignadas las cuentas</param>
        /// <returns>ViewResult</returns>
        [HttpPost]
        public ActionResult AssignAudit(string date, string auditor)
        {
            if (Session["Grp_Codigo"].ToString().Equals("adm"))
            {
                ViewBag.totalAsignado = new AuditoriaBusiness().AssignAudit(date, auditor, Session["UserCode"].ToString()); ;
                List<Entities.UnAssignedAudit> unAssignedAudits = new AuditoriaBusiness().GetUnAssignedAudit();
                return View("Index", unAssignedAudits);        
            }

            return RedirectToAction("Index");
        }
	}
}

SRAM/Controllers/AuditoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BisnessLogic;
using SRAM.Models;

namespace SRAM.Controllers
{
    public class AuditoryController : Controller
    {
        /// <summary>
        /// Permite obtener las auditorias pendientes.
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Index()
        {
            List<Auditoria> pendingAudits = new AuditoriaBusiness().GetPendingAudit("", "");
            return View(pendingAudits);
        }

        /// <summary>
        /// Permite reasignar una cuanta.
        /// </summary>
        /// <param name="input">Input model con la data para realizar la reasignacion</param>
        /// <returns>JsonResult</returns>
        [HttpPost]
        public JsonResult ReAssign(ReassignInput input)
        {
            bool reasignacionNoRealizada = false;
            if (input.Assigments != null)
            {
                reasignacionNoRealizada = new AuditoriaBusiness().ReAssignAudit(input.Assigments, input.User, Convert.ToInt32(Session["UserCode"]));
            }
            else
            {
                return Json(new { WARNING = "Las asignaciones estan llegando vacias." }, JsonRequestBehavior.AllowGet);
            }

            if (!reasignacionNoRealizada)
            {
                return Json(new { ERROR = "Error al realizar la reasignacion." }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { OK = "Reasignacion realizada." }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Permite auditar una cuenta.
        /// </summary>
        /// <param name="auditResult">Input model con la data para realizar la auditoria</param>
        /// <returns>JsonResult</returns>
        [HttpPost]
        public JsonResult Audit(Entities.AuditResult auditResult)
        {
            auditResult.UserCode = Session["UserCode"].ToString();
            bool resultset = new AuditoriaBusiness().Auditar(auditResult.AssignmentId, auditResult.AccountId, auditResult.AuditorComments,
                auditResult.Answers.ToArray(), auditResult.UserCode, auditResult.IsDescargaAdministrativo, auditResult.IsDescargarReauditoria);

            if (resultset)
            {
                return Json(new { OK = "Cuanta auditada exitosamente." }, JsonRequestBehavior.AllowGet);
            }

            return Json(new { ERROR = "La cuenta no se pudo auditar." }, JsonRequestBehavior.AllowGet);

        }

        /// <summary>
        /// Obtiene los detalles que ve el auditor para poder realizar la auditoria.
        /// </summary>
        /// <param name="AssignmentId">Id de la asignacion, represanta la cuanta que se esta auditando</param>
        /// <returns>JsonResult</returns>
        public JsonResult GetTransactionInfoByAssignment(string AssignmentId)
        {
            List<Entities.PenddingAudit> pendingAudit = new AuditoriaBusiness().GetAcctInfoByAssignment(AssignmentId);

            return Json(new { transaccion = pendingAudit }, JsonRequestBehavior.AllowGet);
        }

        /// <summary>
        /// Permite obtener las lista de la auditorias realizadas.
        /// </summary>
        /// <param name="SubscrId">Id de cliente</param>
        /// <param name="Auditor">Quien realiza la auditoria</param>
        /// <param name="SalesDate">La fecha de venta</param>
        /// <param name="CreationDate">Fecha de creacion</param>
        /// <param name="CallId">Id de la llamada</param>
        /// <param name="PhoneNo">Numero telefonico</param>
        /// <returns>ViewResult</returns>
        [HttpGet]
        public ViewResult SearchAuditedAccount()
        {
            ViewBag.input = new InputSearchAuditory();
            ViewBag.Error = null;
            ViewBag.doneAudit = true;
            return View(new List<Auditoria>());
        }

        /// <summary>
        /// Permite obtener las lista de la auditorias realizadas.
        /// </summary>
        /// <param name="SubscrId">Id de cliente</param>
        /// <param name="Auditor">Quien realiza la auditoria</param>
        /// <param name="SalesDate">La fecha de venta</param>
        /// <param name="CreationDate">Fecha de creacion</param>
        /// <param name="CallId">Id de la llamada</param>
        /// <param name="PhoneNo">Numero telefonico</param>
        /// <returns>ViewResult</returns>
        [HttpPost]
        public ActionResult SearchAuditedAccount(InputSearchAuditory input)
        {
            IEnumerable<Entities.Auditoria> transaccion = null;
            bool isEnyEmpty = (string.IsNullOrEmpty(input.SubscrId) && string.IsNullOrEmpty(input.Auditor) && string.IsNullOrEmpty(input.SalesDate) &&
                string.IsNullOrEmpty(input.CreationDate) && string.IsNullOrEmpty(input.CallId) && string.IsNullOrEmpty(input.PhoneNo));
            ViewBag.doneAudit = true;
            if (isEnyEmpty)
            {
                ViewBag.input = input;
                ViewBag.Error = "Debe proveer al menos uno de los campos requeridos.";
                return View(new List<Auditoria>());
            }
            else
            {
                transaccion = new AuditoriaBusiness().GetDoneAudits(input.SubscrId, input.Auditor, input.SalesDate, input.CreationDate, input.CallId, input.PhoneNo);
            }

            ViewBag.input = input;
            ViewBag.Error = null;
            return View(transaccion);
        }

        /// <summary>
        /// Permite eliminar una auditoria, solo es realizada por un administrador.
        /// </summary>
        /// <param name="AuditId"></param>
        /// <param name="UserCode"></param>
        /// <returns></returns>
        public JsonResult DeleteAudit(int? AuditId)
        {
            string role = HttpContext.Session["grp_codigo"].ToString();

            bool resulset = false;

            if (role == "adm")
            {
                resulset = new AuditoriaBusiness().DeleteAudit(AuditId, Session["UserCode"].ToString());
            }

            if (resulset)
            {
                return Json(new { OK = "Auditoria eliminada correctamete." }, JsonRequestBehavior.AllowGet);    
            }

            return Json(new { ERROR = "Error al eliminar la auditoria." }, JsonRequestBehavior.AllowGet);
        }
	}
}

SRAM/Controllers/PendingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;
using BisnessLogic;
using SRAM.Models;

namespace SRAM.Controllers
{
    public class PendingController : Controller
    {
        /// <summary>
        /// Muestra una lista con los pendientes a auditar.
        /// </summary>
        /// <returns>ViewResult</returns>
        public ActionResult Index()
        {
            ViewBag.input = new InputSearchAuditory();
            ViewBag.Error = null;
            ViewBag.doneAudit = false;
            List<Auditoria> pendingAudits = null;
            string role = Session["Grp_Codigo"].ToString();

            if (role.Equals("adm"))
            {
                pendingAudits = new AuditoriaBusiness().GetPendingAudit("", "");
                return View(pendingAudits);
            }

            pendingAudits = new AuditoriaBusiness().GetPendingAudit(Session["UserCode"].ToString(), "");
            return View(pendingAudits);
            
        }

        /// <summary>
        /// Muestra una lista con los pendientes a auditar. Filtrando por artista y por fecha.
        /// </summary>
        /// <param name="userCode">Codigo del usuario logueado</param>
        /// <param name="salesDate">Fecha de venta</param>
        /// <returns>ViewResult</returns>
        [HttpPost]
        public ViewResult GetPendingAud(string userCode, string salesDate)
        {
            ViewBag.input = new InputSearchAuditory();
            ViewBag.Error = null;
            ViewBag.doneAudit = false;
            var auditoriasPendientes = new AuditoriaBusiness().GetPendingAudit(userCode, salesDate);
            return View("Index",auditoriasPendientes);
        }
	}
}

SRAM/Controllers/SubscriberController.cs
using BisnessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;

namespace SRAM.Controllers
{
    public class SubscriberController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Permite obtener la informacion de credito del subscriber
        /// </summary>
        /// <param name="SubscrId">cliente</param>
        /// <param name="CanvEdition">edicion de la camplania</param>
        /// <param name="CanvCode">campania</param>
        /// <param name="Book">libro</param>
        /// <returns>List<Credit></returns>
        public JsonResult GetCredits(int SubscrId, int CanvEdition, string CanvCode, string Book)
        {
            List<Credit> credits = new SubscriberBusiness().GetCredit(SubscrId, CanvEdition, CanvCode, Book);
            return Json(new { credit = credits }, JsonRequestBehavior.AllowGet);
        }
        
        /// <summary>
        /// Permite obtener la infromacion de reclamo de un cliente.
        /// </summary>
        /// <param name="SubscrId">cliente</param>
        /// <param name="CanvEdition">edicon de la campania</param>
        /// <param name="CanvCode">campania</param>
        /// <param name="Book">libro</param>
        /// <returns>List<Claim></returns>
        public JsonResult GetClaims(int SubscrId, int CanvEdition, string CanvCode, string Book)
        {
            List<Claim> claims = new SubscriberBusiness().GetClaims(SubscrId, CanvEdition, CanvCode, Book);
            return Json(new { claim = claims }, JsonRequestBehavior.AllowGet);
        }
	}
}

SRAM/Views/Shared/_AuditTable.cshtml
@model List<Entities.Auditoria>

<div class="col-sm-12">
    <div class="panel">
        <div class="panel-heading">
            <h3 class="panel-title">Pendientes a Auditar</h3>
        </div>
        <div class="panel-body">

            <div class="pad-btm form-inline">
                <div class="row">
                    <div class="col-sm-6">
                        <div class="pad-btm">
                            <button id="demo-foo-collapse" class="btn btn-info"><i class="fa fa-compress" aria-hidden="true"></i></button>
                            <button id="demo-foo-expand" class="btn btn-warning"><i class="fa fa-expand" aria-hidden="true"></i></button>
                            <label class="form-inline">
                                Show
                                <select id="demo-show-entries" class="form-control input-sm">
                                    <option value="5">5</option>
                                    <option value="10">10</option>
                                    <option value="15">15</option>
                                    <option value="20">20</option>
                                </select>
                                entries
                            </label>
                        </div>
                    </div>
                    <div class="col-sm-6 text-xs-center text-right">
                        <div class="form-group">
                            <input id="demo-foo-search" type="text" placeholder="Search" class="form-control" autocomplete="off">
                        </div>
                    </div>
                </div>
            </div>
            <table id="pending-table" class="table toggle-circle" data-page-size="10">
                <thead>
                    <tr>
                        <th data-sort-ignore="true">
                            <input type="checkbox" class="checked-all-assigment"/>
                        </th>
                        <th data-toggle="true" class="footable-first-column">Razón Social</th>
                        <th>Subs Id</th>
                        <th>Teléfono</th>
                        <th>Canvass</th>                        
                        <th>Ejecutivo</th>
                        <th data-hide="phone, tablet">Unidad</th>
                        <th data-hide="phone, tablet">Fecha RCP</th>
                        <th data-hide="phone, tablet">Compañía</th>
                        <th data-hide="phone, tablet">Tipo de Servicio</th>
                        <th data-sort-ignore="true" style="width:180px;"></th>
                        <th data-hide="all">Control Verbal Call Id</th>
                        <th data-hide="all">Book Code</th>
                        <th data-hide="all">Cargo</th>
                        <th data-hide="all">Venta</th>
                        <th data-hide="all">PDC Dimmas</th>
                        <th data-hide="all">PDC Codetel</th>
                        <th data-hide="all">Comentario Ejecutivo</th>                                                
                        <th data-hide="all">Call Id</th>
                        <th data-hide="all">Auditor Asignado</th>                        
                        <th data-hide="all">Previo Call Id</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr data-subscriber="@item.SubscriberId" data-canv-edition="@item.CanvEdition" data-canv-code="@item.Canvass" data-book-code="@item.BookCodeDetail">
                            <td>
                                <input type="checkbox" class="checked-assigment" value="@item.AssignmentId"/>
                            </td>
                            <td>@item.RazonSocial</td>
                            <td>@item.SubscriberId</td>
                            <td>@item.Telefono</td>
                            <td>@item.Canvass</td>                            
                            <td>@item.Ejecutivo</td>
                            <td>@item.Unidad</td>
                            <td>@item.FechaRPC</td>                            
                            <td>@item.Compania</td>
                            <td>@item.TipoDeServicio</td>
                            <td>
                                <div class="btn-group-xs">
                                    @if (@item.HassCredit)
                                    {
                                        <button type="button" class="btn btn-primary show-credit" data-url="@Url.Action("GetCredits", "Subscriber")">Credit</button>
                                    }

                                    @if (@item.HassClaim)
                                    {
                                    <button type="button" class="btn btn-info show-claim" data-url="@Url.Action("GetClaims", "Subscriber")">Claim</button>
                                    }                                    
                                    <button type="button" class="btn btn-default audit-command-button" data-assigment-id="@item.AssignmentId" data-account-id="@item.AccountId" data-url="@Url.Action("GetTransactionInfoByAssignment", "Auditory")">Auditar</button>
                                </div>
                            </td>
                            <td>@item.ControlVerballCallId</td>
                            <td>@item.BookCodeDetail</td>
                            <td>@item.Cargo</td>
                            <td>@item.Venta</td>
                            <td>@item.PDCDimmas</td>
                            <td>@item.PDCCodetel</td>
                            <td>@item.ComentarioEjecutivo</td>                                                        
                            <td>@item.CallId</td>
                            <td>@item.AuditorAsignado</td>
                            
                            @if (item.PrevioCallId != "X")
                            {
                                <td><span class="label label-table label-primary">@item.PrevioCallId</span></td>
                            }
                            else
                            {
                                <td></td>
                            }
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5">
                            <div class="text-left">
                                <ul class="pagination"></ul>
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

SRAM/Views/Shared/_ClaimModal.cshtml
<div class="modal" id="claim-modal" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-body">
                <table class="table" data-url="@Url.Action("GetClaims", "Subscriber")" id="claim-table">
                    <caption class="text-center"><h3>Cliente con Reclamos</h3></caption>
                    <thead>
                        <tr>
                            <th>No. Reclamo</th>
                            <th>Libro</th>
                            <th>Descripcion Reclamo</th>
                            <th>Comentario Cliente</th>
                            <th>Canv Code</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>

            <!--Modal footer-->
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            </div>
        </div>
    </div>
</div>

SRAM/Views/Shared/_CreditModal.cshtml
<div class="modal" id="credit-modal" role="dialog" tabindex="-1" aria-labelledby="demo-default-modal" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <!--Modal body-->
            <div class="modal-body">
                <table class="table" data-ur="@Url.Action("GetCredits","Subscriber")" id="credit-table">
                    <caption class="text-dark text-center"><h3>Informacion de Reclamos</h3></caption>
                    <thead>
                        <tr>
                            <th>No. Reclamo</th>
                            <th>Libro</th>
                            <th>Comentario Cliente</th>
                            <th>Info Desc</th>
                        </tr>
                    </thead>
                    <tbody></tbody>
                </table>
            </div>
            <!--Modal footer-->
            <div class="modal-footer">
                <button data-dismiss="modal" class="btn btn-default" type="button">Close</button>
            </div>
        </div>
    </div>
</div>

SRAM/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    
    <link href="~/Content/bootstrap.min.css" rel="stylesheet">

    <link href="~/Content/nifty.min.css" rel="stylesheet">

    <link href="~/Content/themes/type-c/theme-light.min.css" rel="stylesheet" />
    
    <link href="~/Content/themify-icons/themify-icons.min.css" rel="stylesheet">
        
    <link href="~/Content/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet">

    <link href="~/Content/plugins/fooTable/css/footable.core.min.css" rel="stylesheet" />

    <link href="~/Content/loading.css" rel="stylesheet" />

    <link href="~/Content/Site.css" rel="stylesheet">

    <link href="~/Content/plugins/bootstrap-select/bootstrap-select.min.css" rel="stylesheet" />

    @RenderSection("styles", false)
</head>
<body>
    <div id="container" class="mainnav-lg jumping mainnav-fixed navbar-fixed">

        <!--NAVBAR-->
        <!--===================================================-->
        <header id="navbar">
            <div id="navbar-container" class="boxed">

                <!--Brand logo & name-->
                <!--================================-->
                <div class="navbar-header">
                    <a class="navbar-brand">
                        <img src="~/Content/img/logo.png" alt="SRAM Logo" class="brand-icon">
                        <div class="brand-title">
                            <span class="brand-text" style="padding-left:15px; display:inline-block;"> SRAM</span>
                        </div>
                    </a>
                </div>
                <!--================================-->
                <!--End brand logo & name-->
                <!--Navbar Dropdown-->
                <!--================================-->
                <div class="navbar-content clearfix">
                    <ul class="nav navbar-top-links pull-left">

                        <!--Navigation toogle button-->
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <li class="tgl-menu-btn">
                            <a class="mainnav-toggle" href="#">
                                <i class="ti-view-list icon-lg"></i>
                            </a>
                        </li>
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <!--End Navigation toogle button-->
                        <!--Notification dropdown-->
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->

                    </ul>
                    <ul class="nav navbar-top-links pull-right">

                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <!--End language selector-->
                        <!--User dropdown-->
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <li id="dropdown-user" class="dropdown">
                            <a href="#" data-toggle="dropdown" class="dropdown-toggle text-right">
                                <span class="pull-right">
                                    <img class="img-circle img-user media-object" src="~/Content/img/av1.png" alt="Profile Picture">
                                </span>
                                <div class="username hidden-xs">@Session["UserName"]</div>
                            </a>


                            <div class="dropdown-menu dropdown-menu-md dropdown-menu-right panel-default">

                                <!-- Dropdown footer -->
                                <div class="pad-all text-right">
                                    <a class="btn btn-primary">
                                        <i class="ti-unlock icon-fw"></i> Logout
                                    </a>
                                </div>
                            </div>
                        </li>
                        <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                        <!--End user dropdown-->

                    </ul>
                </div>
                <!--================================-->
                <!--End Navbar Dropdown-->

            </div>
        </header>
        <!--===================================================-->
        <!--END NAVBAR-->

        <div class="boxed">
            <div id="content-container">
                <div class="loader-wrapper" style="display:none">
                    <div class="loader"></div>
                    <div class="loader-section section-left"></div>
                    <div class="loader-section section-right"></div>
                </div>
                <!--Page Title-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <div class="row">
                    <div class="col-xs-12">
                        <div id="page-title" class="transparent-nav-container">
                            <div class="transparent-nav-child-brand">
                                <h1 class="page-header text-overflow">SRAM</h1>
                            </div>
                        </div>
                    </div>
                </div>
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <!--End page title-->
                <!--Breadcrumb-->
                <!--~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~-->
                <div id="page-content" style="padding:30px;">
                    @RenderBody()
                </div>
                <!--===================================================-->
                <!--End page content-->


            </div>
            <!--===================================================-->
            <!--END CONTENT CONTAINER-->
            <!--MAIN NAVIGATION-->
            <!--===================================================-->
            <nav id="mainnav-container">
                <div id="mainnav">
                    <div id="mainnav-menu-wrap">
                        <div class="nano">
                            <div class="nano-content">
                                <ul id="mainnav-menu" class="list-group">
                                    <li class="active-link">
                                        <a href="@Url.Action("Index", "Pending")" class="can-show-loading">
                                            <i class="fa fa-headphones" aria-hidden="true"></i>
                                            <span class="menu-title">
                                                <strong>Pendientes de Auditar</strong>
                                            </span>
                                        </a>
                                    </li>


                                    @if (Session["Grp_Codigo"].ToString().Equals("adm"))
                                    {
                                        <li class="active-link">
                                            <a href="@Url.Action("Index", "Assign")" class="can-show-loading">
                                                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                                                <span class="menu-title">
                                                    <strong>Asignar</strong>
                                                </span>
                                            </a>
                                        </li>
                                    }


                                    <li class="active-link">
                                        <a href="@Url.Action("SearchAuditedAccount", "Auditory")" class="can-show-loading">
                                            <i class="fa fa-search" aria-hidden="true"></i>
                                            <span class="menu-title">
                                                <strong>Buscar Auditorias</strong>
                                            </span>
                                        </a>
                                    </li>

                                    @if (Session["Grp_Codigo"].ToString().Equals("adm"))
                                    {
                                        <li class="active-link">
                                            <a href="@Url.Action("Index","Report")" class="can-show-loading">
                                                <i class="fa fa-file-excel-o"></i>
                                                <span class="menu-title">
                                                    <strong>Reportes</strong>
                                                </span>
                                            </a>
                                        </li>
                                    }

                                </ul>

                            </div>
                        </div>
                    </div>
                    <!--================================-->
                    <!--End menu-->

                </div>
            </nav>

        </div>

        <!--===================================================-->
        <!-- END FOOTER -->
        <!-- SCROLL TOP BUTTON -->
        <!--===================================================-->
        <button id="scroll-top" class="btn"><i class="fa fa-chevron-up"></i></button>
        <!--===================================================-->



    </div>

    <script src="~/Scripts/js/jquery-2.2.1.min.js"></script>

    <script src="~/Scripts/js/bootstrap.min.js"></script>

    <script src="~/Scripts/js/fastclick.min.js"></script>

    <script src="~/Scripts/js/nifty.min.js"></script>

    <script src="~/Content/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>

    <script src="~/Content/plugins/fooTable/dist/footable.all.min.js"></script>

    <script src="~/Content/plugins/bootbox/bootbox.min.js"></script>

    <link href="~/Content/plugins/magic-check/css/magic-check.min.css" rel="stylesheet" />

    <script src="~/Scripts/Utils.js"></script>

    <script src="~/Scripts/handlebars-v4.0.10.js"></script>

    @RenderSection("scripts", required: false)

    <script>
        $(".can-show-loading").on("click", function () {
            showColorLoading();
        });
    </script>
</body>
</html>