SRAM/Controllers/AssignController.cs
using BisnessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SRAM.Controllers
{
    public class AssignController : Controller
    {
        /// <summary>
        /// Permite obtener las cuentas pendientes en asignar.
        /// </summary>
        /// <returns>ActionResult</returns>
        public ActionResult Index()
        {
            ViewBag.totalAsignado = 0;
            List<Entities.UnAssignedAudit> unAssignedAudits = new AuditoriaBusiness().GetUnAssignedAudit();
            return View(unAssignedAudits);
        }

        /// <summary>
        /// Permite asignar cuentas a usuarios.
        /// </summary>
        /// <param name="date">Fechas de las asignaciones</param>
        /// <param name="auditor">Usuarios a quienes le seran asignadas las cuentas</param>
        /// <returns>ViewResult</returns>
        [HttpPost]
        public ActionResult AssignAudit(string date, string auditor)
        {
            if (Session["Grp_Codigo"].ToString().Equals("adm"))
            {
                ViewBag.totalAsignado = new AuditoriaBusiness().AssignAudit(date, auditor, Session["UserCode"].ToString()); ;
                List<Entities.UnAssignedAudit> unAssignedAudits = new AuditoriaBusiness().GetUnAssignedAudit();
                return View("Index", unAssignedAudits);        
            }

            return RedirectToAction("Index");
        }
	}
}

SRAM/Controllers/AuditorController.cs
using BisnessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SRAM.Controllers
{
    public class AuditorController : Controller
    {
        //
        // GET: /Auditor/
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Permite obtener los auditores, desde sql server, para la app de sra
        /// </summary>
        /// <returns>JsonResult</returns>
        public JsonResult GetAuditors()
        {
            var auditors = new AuditorBusiness().GetAuditors();
            return Json(new { auditors = auditors }, JsonRequestBehavior.AllowGet);
        }
	}
}

SRAM/Controllers/SubscriberController.cs
using BisnessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Entities;

namespace SRAM.Controllers
{
    public class SubscriberController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// Permite obtener la informacion de credito del subscriber
        /// </summary>
        /// <param name="SubscrId">cliente</param>
        /// <param name="CanvEdition">edicion de la camplania</param>
        /// <param name="CanvCode">campania</param>
        /// <param name="Book">libro</param>
        /// <returns>List<Credit></returns>
        public JsonResult GetCredits(int SubscrId, int CanvEdition, string CanvCode, string Book)
        {
            List<Credit> credits = new SubscriberBusiness().GetCredit(SubscrId, CanvEdition, CanvCode, Book);
            return Json(new { credit = credits }, JsonRequestBehavior.AllowGet);
        }
        
        /// <summary>
        /// Permite obtener la infromacion de reclamo de un cliente.
        /// </summary>
        /// <param name="SubscrId">cliente</param>
        /// <param name="CanvEdition">edicon de la campania</param>
        /// <param name="CanvCode">campania</param>
        /// <param name="Book">libro</param>
        /// <returns>List<Claim></returns>
        public JsonResult GetClaims(int SubscrId, int CanvEdition, string CanvCode, string Book)
        {
            List<Claim> claims = new SubscriberBusiness().GetClaims(SubscrId, CanvEdition, CanvCode, Book);
            return Json(new { claim = claims }, JsonRequestBehavior.AllowGet);
        }
	}
}

SRAM/Views/Assign/Index.cshtml
@model List<Entities.UnAssignedAudit>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";

    var unassignedSummary = Model.GroupBy(u => u.FechaVenta).Select(u => new {
        Date = u.Key,
        Count = u.Count()
    }).ToList();
}

@section styles{
    <style>
        div.footable-row-detail-name {
            width: 200px !important;
        }
   </style>

}

<div class="row">
    <div class="col-sm-12">
        <!-- Row selection and deletion (multiple rows) -->
        <!--===================================================-->
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Asignaciones Pendientes</h3>
            </div>
            <div class="panel-body">
                @if (ViewBag.totalAsignado > 0)
                {
                    <div class="alert alert-primary col-sm-12 text-center" style="font-size:15px;">
                        <button class="close" data-dismiss="alert"><i class="pci-cross pci-circle"></i></button>
                        <strong>Info!</strong> RDV asignado exitosamente. Se asignaron un total de: @ViewBag.totalAsignado cuentas. : )
                    </div>
                }

                <select class="selectpicker" id="auditors-select-piker" multiple title="Auditores" data-width="50%" data-url="@Url.Action("GetAuditors", "Auditor")"></select>
                <table id="pedding-assignment" class="table table-striped" width="100">
                    <thead>
                        <tr>
                            <th>Fecha RDV</th>
                            <th>Cantidad</th>
                            <th>Asignar</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var sum in unassignedSummary)
                        {
                            <tr>
                                <td class="sales-date">@sum.Date</td>
                                <td class="pn-assig-acc">@sum.Count</td>
                                <td>
                                    <button class="btn btn-primary asignar-pendiente"><i class="fa fa-thumb-tack" aria-hidden="true"></i></button>
                                </td>
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td class="text-danger" style="text-align:right">Total de pendientes:</td>
                            <td class="text-danger" id="total-pending"></td>
                            <td></td>
                        </tr>
                    </tfoot>
                </table>
                <form action="@Url.Action("AssignAudit", "Assign")" method="post" id="form-assign-auditory">
                    <input type="hidden" name="date" value="" />
                    <input type="hidden" name="auditor" value="" />

                </form>
            </div>
        </div>
        <!--===================================================-->
        <!-- End Row selection and deletion (multiple rows) -->
    </div>
    <div class="col-sm-12">
        <div class="panel">
            <div class="panel-heading">
                <h3 class="panel-title">Pendientes</h3>
            </div>
            <div class="panel-body">

                <div class="pad-btm form-inline">
                    <div class="row">
                        <div class="col-sm-6">
                            <div class="pad-btm">
                                <button id="demo-foo-collapse" class="btn btn-info"><i class="fa fa-compress" aria-hidden="true"></i></button>
                                <button id="demo-foo-expand" class="btn btn-warning"><i class="fa fa-expand" aria-hidden="true"></i></button>
                                <label class="form-inline">
                                    Show
                                    <select id="demo-show-entries" class="form-control input-sm">
                                        <option value="5">5</option>
                                        <option value="10">10</option>
                                        <option value="15">15</option>
                                        <option value="20">20</option>
                                    </select>
                                    entries
                                </label>
                            </div>
                        </div>
                        <div class="col-sm-6 text-xs-center text-right">
                            <div class="form-group">
                                <input id="demo-foo-search" type="text" placeholder="Search" class="form-control" autocomplete="off">
                            </div>
                        </div>
                    </div>
                </div>
                <table id="pending-table" class="table toggle-circle" data-page-size="10">
                    <thead>
                        <tr>
                            <th data-toggle="true" class="footable-first-column">Subs Id</th>
                            <th>Subscriber Name</th>
                            <th>Teléfono</th>
                            <th>Canvass</th>
                            <th>Canvass Edition</th>
                            <th>Ejecutivo</th>
                            <th data-hide="phone, tablet">Unidad</th>
                            <th data-hide="phone, tablet">Venta</th>
                            <th data-hide="phone, tablet">Fecha Venta</th>
                            <th data-sort-ignore="true" style="width:180px;"></th>
                            <th data-hide="all">Cargo</th>
                            <th data-hide="all">Call Id</th>                            
                            <th data-hide="all">Book Code</th>
                            <th data-hide="all">Account Id</th>
                            <th data-hide="all">Conmentario</th>
                            <th data-hide="all">PDC Dimmas</th>
                            <th data-hide="all">PDC Codetel</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr data-subscriber="@item.SubscriberId" data-canv-edition="@item.CanvEdition" data-canv-code="@item.Canvass" data-book-code="@item.BookCodeDetail">
                                <td>@item.SubscriberId</td>
                                <td>@item.SubscriberName</td>
                                <td>@item.Telefono</td>
                                <td>@item.Canvass</td>
                                <td>@item.CanvEdition</td>
                                <td>@item.Ejecutivo</td>
                                <td>@item.Unidad</td>
                                <td>@item.Venta</td>
                                <td>@item.FechaVenta</td>
                                <td>
                                    <div class="btn-group-xs">
                                        @if (@item.HassCredit)
                                        {
                                            <button type="button" class="btn btn-primary show-credit" data-url="@Url.Action("GetCredits", "Subscriber")">Credit</button>
                                        }

                                        @if (@item.HassClaim)
                                        {
                                            <button type="button" class="btn btn-info show-claim" data-url="@Url.Action("GetClaims", "Subscriber")">Claim</button>
                                        }
                                    </div>
                                </td>
                                <td>@item.Cargo</td>
                                <td>@item.CallId</td>
                                <td>@item.BookCodeDetail</td>
                                <td>@item.AccountId</td>
                                <td>@item.Comentario</td>
                                <td>@item.PDCDimmas</td>
                                <td>@item.PDCCodetel</td>                                
                            </tr>
                        }
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="5">
                                <div class="text-left">
                                    <ul class="pagination"></ul>
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
    </div>
</div>

@RenderPage("~/Views/Shared/_CreditModal.cshtml")
@RenderPage("~/Views/Shared/_ClaimModal.cshtml")
@RenderPage("~/Views/Shared/Handlebar/Templates.cshtml")

@section scripts{

    <script src="~/Content/plugins/bootstrap-select/bootstrap-select.min.js"></script>
    <script src="~/Scripts/sram/class.js"></script>
    <script src="~/Scripts/sram/modules.js"></script>
    <script src="~/Scripts/sram/assign.js"></script>
}